/* AMP Mountain Site — content packs (jobs and Education posts)
   Jobs: 53 Active+Open matched Webflow postings (audit C+D) synced 2026-09-06.
   Source: website-jobs.json + Bullhorn owner map. No invented towns/hospitals.
   Bucket A stale (51) and Bucket B missing (54) excluded. */
window.AMP_CONTENT = {
  specialties: [
    { id: "fm", label: "Family Medicine", blurb: "Clinic-first weeks with room for life outside the trail." },
    { id: "family_medicine_with_ob", label: "Family Medicine (with OB)" },
    { id: "obg", label: "Obstetrics & Gynecology", blurb: "Practice-first OB/GYN roles — schedule and package on a call." },
    { id: "internal_medicine_general", label: "Internal Medicine: General" },
    { id: "emergency_medicine", label: "Emergency Medicine" },
    { id: "psychiatry_general", label: "Psychiatry: General" },
    { id: "hospitalist_internal_medicine", label: "Hospitalist: Internal Medicine" },
    { id: "cardiology_noninvasive", label: "Cardiology: Noninvasive" },
    { id: "cardiology_invasive_interventional", label: "Cardiology: Invasive-Interventional" },
    { id: "anesthesiology", label: "Anesthesiology" },
    { id: "surgery_general", label: "Surgery: General" },
    { id: "pediatrics_general", label: "Pediatrics: General" },
    { id: "urgent_care", label: "Urgent Care" },
    { id: "allergy_immunology", label: "Allergy / Immunology" },
    { id: "anesthesiology_cardiology", label: "Anesthesiology: Cardiology" },
    { id: "anesthesiology_pain_management", label: "Anesthesiology: Pain Management" },
    { id: "bariatrics_nonsurgical_obesity_medicine", label: "Bariatrics (Nonsurgical) / Obesity Medicine" },
    { id: "cardiology_electrophysiology", label: "Cardiology: Electrophysiology" },
    { id: "cardiology_invasive", label: "Cardiology: Invasive" },
    { id: "certified_registered_nurse_anesthetist", label: "Certified Registered Nurse Anesthetist" },
    { id: "critical_care_intensivist", label: "Critical Care: Intensivist" },
    { id: "dental", label: "Dentistry", blurb: "Dental and DSOs with clear package tease." },
    { id: "dermatology", label: "Dermatology" },
    { id: "dermatology_dermatopathology", label: "Dermatology: Dermatopathology" },
    { id: "dermatology_mohs_surgery", label: "Dermatology: Mohs Surgery" },
    { id: "dietician_nutritionist", label: "Dietician / Nutritionist" },
    { id: "endocrinology_metabolism", label: "Endocrinology / Metabolism" },
    { id: "family_medicine_ambulatory_only_no_inpatient_work", label: "Family Medicine: Ambulatory Only (No Inpatient Work)" },
    { id: "family_medicine_sports_medicine", label: "Family Medicine: Sports Medicine" },
    { id: "gi", label: "Gastroenterology", blurb: "Procedure and clinic mix with clear schedule tease." },
    { id: "gastroenterology_hepatology", label: "Gastroenterology: Hepatology" },
    { id: "geriatrics", label: "Geriatrics" },
    { id: "hematology_oncology", label: "Hematology / Oncology" },
    { id: "hematology_oncology_oncology_only", label: "Hematology / Oncology: Oncology (Only)" },
    { id: "hospice_palliative_care", label: "Hospice / Palliative Care" },
    { id: "hospitalist_family_medicine", label: "Hospitalist: Family Medicine" },
    { id: "hospitalist_neurology", label: "Hospitalist: Neurology" },
    { id: "hospitalist_nocturnist", label: "Hospitalist: Nocturnist" },
    { id: "hospitalist_ob_gyn", label: "Hospitalist: OB/GYN" },
    { id: "hyperbaric_medicine_wound_care", label: "Hyperbaric Medicine / Wound Care" },
    { id: "infectious_disease", label: "Infectious Disease" },
    { id: "internal_medicine_ambulatory_only_no_inpatient_work", label: "Internal Medicine: Ambulatory Only (No Inpatient Work)" },
    { id: "licensed_clinical_social_worker", label: "Licensed Clinical Social Worker" },
    { id: "nephrology", label: "Nephrology" },
    { id: "nephrology_transplant", label: "Nephrology: Transplant" },
    { id: "neuro", label: "Neurology", blurb: "Outpatient and hybrid neuro paths with guide support." },
    { id: "neurology_epilepsy_eeg", label: "Neurology: Epilepsy / EEG" },
    { id: "neurology_neurocritical_care", label: "Neurology: Neurocritical Care" },
    { id: "neurology_neuromuscular_medicine", label: "Neurology: Neuromuscular Medicine" },
    { id: "neurology_stroke_medicine", label: "Neurology: Stroke Medicine" },
    { id: "nurse_midwife", label: "Nurse Midwife" },
    { id: "nurse_practitioner_primary_care", label: "Nurse Practitioner (Primary Care)" },
    { id: "nurse_practitioner_surgical", label: "Nurse Practitioner (Surgical)" },
    { id: "nurse_practitioner_behavioral_medicine", label: "Nurse Practitioner: Behavioral Medicine" },
    { id: "nurse_practitioner_emergency_medicine", label: "Nurse Practitioner: Emergency Medicine" },
    { id: "nurse_practitioner_family_medicine_with_ob", label: "Nurse Practitioner: Family Medicine (with OB)" },
    { id: "nurse_practitioner_family_medicine_without_ob", label: "Nurse Practitioner: Family Medicine (without OB)" },
    { id: "nurse_practitioner_hospitalist_primary_care", label: "Nurse Practitioner: Hospitalist (Primary Care)" },
    { id: "nurse_practitioner_psychiatry", label: "Nurse Practitioner: Psychiatry" },
    { id: "ob_gyn_gynecological_oncology", label: "OB/GYN: Gynecological Oncology" },
    { id: "ob_gyn_gynecology_only", label: "OB/GYN: Gynecology (Only)" },
    { id: "ob_gyn_maternal_and_fetal_medicine", label: "OB/GYN: Maternal and Fetal Medicine" },
    { id: "ob_gyn_minimally_invasive_gynecologic_surgery", label: "OB/GYN: Minimally Invasive Gynecologic Surgery" },
    { id: "ob_gyn_reproductive_endocrinology", label: "OB/GYN: Reproductive Endocrinology" },
    { id: "ob_gyn_urogynecology", label: "OB/GYN: Urogynecology" },
    { id: "occupational_medicine", label: "Occupational Medicine" },
    { id: "occupational_therapist", label: "Occupational Therapist" },
    { id: "ophthalmology", label: "Ophthalmology" },
    { id: "optometrist", label: "Optometrist" },
    { id: "orthopedic_surgery_foot_and_ankle", label: "Orthopedic Surgery: Foot and Ankle" },
    { id: "orthopedic_surgery_general", label: "Orthopedic Surgery: General" },
    { id: "orthopedic_surgery_hand", label: "Orthopedic Surgery: Hand" },
    { id: "orthopedic_surgery_hip_and_joint", label: "Orthopedic Surgery: Hip and Joint" },
    { id: "orthopedic_surgery_oncology", label: "Orthopedic Surgery: Oncology" },
    { id: "orthopedic_surgery_shoulder_elbow", label: "Orthopedic Surgery: Shoulder / Elbow" },
    { id: "orthopedic_surgery_spine", label: "Orthopedic Surgery: Spine" },
    { id: "orthopedic_surgery_sports_medicine", label: "Orthopedic Surgery: Sports Medicine" },
    { id: "orthopedic_surgery_trauma", label: "Orthopedic Surgery: Trauma" },
    { id: "otorhinolaryngology", label: "Otorhinolaryngology" },
    { id: "pain_management_nonanesthesia", label: "Pain Management: Nonanesthesia" },
    { id: "pathology_anatomic", label: "Pathology: Anatomic" },
    { id: "pathology_anatomic_and_clinical", label: "Pathology: Anatomic and Clinical" },
    { id: "pathology_clinical", label: "Pathology: Clinical" },
    { id: "pathology_surgical", label: "Pathology: Surgical" },
    { id: "pediatrics_adolescent_medicine", label: "Pediatrics: Adolescent Medicine" },
    { id: "pediatrics_allergy_immunology", label: "Pediatrics: Allergy / Immunology" },
    { id: "pediatrics_anesthesiology", label: "Pediatrics: Anesthesiology" },
    { id: "pediatrics_bone_marrow_transplant", label: "Pediatrics: Bone Marrow Transplant" },
    { id: "pediatrics_cardiology", label: "Pediatrics: Cardiology" },
    { id: "pediatrics_cardiothoracic_surgery", label: "Pediatrics: Cardiothoracic Surgery" },
    { id: "pediatrics_cardiovascular_surgery", label: "Pediatrics: Cardiovascular Surgery" },
    { id: "pediatrics_child_development", label: "Pediatrics: Child Development" },
    { id: "pediatrics_clinical_and_lab_immunology", label: "Pediatrics: Clinical and Lab Immunology" },
    { id: "pediatrics_critical_care_intensivist", label: "Pediatrics: Critical Care / Intensivist" },
    { id: "pediatrics_dermatology", label: "Pediatrics: Dermatology" },
    { id: "pediatrics_emergency_medicine", label: "Pediatrics: Emergency Medicine" },
    { id: "pediatrics_endocrinology", label: "Pediatrics: Endocrinology" },
    { id: "pediatrics_gastroenterology", label: "Pediatrics: Gastroenterology" },
    { id: "pediatrics_genetics", label: "Pediatrics: Genetics" },
    { id: "pediatrics_hematology_oncology", label: "Pediatrics: Hematology / Oncology" },
    { id: "pediatrics_hospitalist", label: "Pediatrics: Hospitalist" },
    { id: "pediatrics_hospitalist_internal_medicine", label: "Pediatrics: Hospitalist-Internal Medicine" },
    { id: "pediatrics_infectious_disease", label: "Pediatrics: Infectious Disease" },
    { id: "pediatrics_internal_medicine", label: "Pediatrics: Internal Medicine" },
    { id: "pediatrics_neonatal_medicine", label: "Pediatrics: Neonatal Medicine" },
    { id: "pediatrics_nephrology", label: "Pediatrics: Nephrology" },
    { id: "pediatrics_neurology", label: "Pediatrics: Neurology" },
    { id: "pediatrics_neurosurgery", label: "Pediatrics: Neurosurgery" },
    { id: "pediatrics_ophthalmology", label: "Pediatrics: Ophthalmology" },
    { id: "pediatrics_orthopedic_surgery", label: "Pediatrics: Orthopedic Surgery" },
    { id: "pediatrics_otorhinolaryngology", label: "Pediatrics: Otorhinolaryngology" },
    { id: "pediatrics_plastic_and_reconstruction_surgery", label: "Pediatrics: Plastic and Reconstruction Surgery" },
    { id: "pediatrics_pulmonology", label: "Pediatrics: Pulmonology" },
    { id: "pediatrics_radiology", label: "Pediatrics: Radiology" },
    { id: "pediatrics_rheumatology", label: "Pediatrics: Rheumatology" },
    { id: "pediatrics_sports_medicine", label: "Pediatrics: Sports Medicine" },
    { id: "pediatrics_surgery", label: "Pediatrics: Surgery" },
    { id: "pediatrics_urgent_care", label: "Pediatrics: Urgent Care" },
    { id: "pediatrics_urology", label: "Pediatrics: Urology" },
    { id: "physiatry_physical_medicine_and_rehabilitation", label: "Physiatry (Physical Medicine and Rehabilitation)" },
    { id: "physical_therapist", label: "Physical Therapist" },
    { id: "physician_assistant_primary_care", label: "Physician Assistant (Primary Care)" },
    { id: "physician_assistant_surgical", label: "Physician Assistant (Surgical)" },
    { id: "physician_assistant_anesthesiology", label: "Physician Assistant: Anesthesiology" },
    { id: "physician_assistant_behavioral_medicine", label: "Physician Assistant: Behavioral Medicine" },
    { id: "physician_assistant_family_medicine_with_ob", label: "Physician Assistant: Family Medicine (with OB)" },
    { id: "physician_assistant_family_medicine_without_ob", label: "Physician Assistant: Family Medicine (without OB)" },
    { id: "physician_assistant_hospitalist_primary_care", label: "Physician Assistant: Hospitalist (Primary Care)" },
    { id: "physician_assistant_orthopedics_surgical", label: "Physician Assistant: Orthopedics (Surgical)" },
    { id: "physician_assistant_psychiatry", label: "Physician Assistant: Psychiatry" },
    { id: "podiatry_general", label: "Podiatry: General" },
    { id: "podiatry_surgery", label: "Podiatry: Surgery" },
    { id: "psychiatry_addiction_medicine", label: "Psychiatry: Addiction Medicine" },
    { id: "psychiatry_behavioral_medicine", label: "Psychiatry: Behavioral Medicine" },
    { id: "psychiatry_chemical_dependency", label: "Psychiatry: Chemical Dependency" },
    { id: "psychiatry_child_and_adolescent", label: "Psychiatry: Child and Adolescent" },
    { id: "psychiatry_forensic", label: "Psychiatry: Forensic" },
    { id: "psychiatry_geriatric", label: "Psychiatry: Geriatric" },
    { id: "psychologist", label: "Psychologist" },
    { id: "pulmonary_medicine_critical_care", label: "Pulmonary Medicine: Critical Care" },
    { id: "pulmonary_medicine_general", label: "Pulmonary Medicine: General" },
    { id: "pulmonary_medicine_general_and_critical_care", label: "Pulmonary Medicine: General and Critical Care" },
    { id: "radiation_oncology", label: "Radiation Oncology" },
    { id: "radiology_diagnostic", label: "Radiology: Diagnostic" },
    { id: "radiology_interventional", label: "Radiology: Interventional" },
    { id: "radiology_neurological", label: "Radiology: Neurological" },
    { id: "radiology_nuclear_medicine", label: "Radiology: Nuclear Medicine" },
    { id: "rheumatology", label: "Rheumatology" },
    { id: "sleep_medicine", label: "Sleep Medicine" },
    { id: "surgery_bariatric", label: "Surgery: Bariatric" },
    { id: "surgery_breast", label: "Surgery: Breast" },
    { id: "surgery_cardiothoracic", label: "Surgery: Cardiothoracic" },
    { id: "surgery_cardiovascular", label: "Surgery: Cardiovascular" },
    { id: "surgery_colon_and_rectal", label: "Surgery: Colon and Rectal" },
    { id: "surgery_endocrine", label: "Surgery: Endocrine" },
    { id: "surgery_endovascular_primary", label: "Surgery: Endovascular (Primary)" },
    { id: "surgery_neurological", label: "Surgery: Neurological" },
    { id: "surgery_oncology", label: "Surgery: Oncology" },
    { id: "surgery_oral", label: "Surgery: Oral" },
    { id: "surgery_plastic_and_reconstruction", label: "Surgery: Plastic and Reconstruction" },
    { id: "surgery_plastic_and_reconstruction_hand", label: "Surgery: Plastic and Reconstruction-Hand" },
    { id: "surgery_thoracic_primary", label: "Surgery: Thoracic (Primary)" },
    { id: "surgery_transplant", label: "Surgery: Transplant" },
    { id: "surgery_transplant_heart", label: "Surgery: Transplant-Heart" },
    { id: "surgery_transplant_heart_lung", label: "Surgery: Transplant-Heart / Lung" },
    { id: "surgery_transplant_kidney", label: "Surgery: Transplant-Kidney" },
    { id: "surgery_transplant_liver", label: "Surgery: Transplant-Liver" },
    { id: "surgery_trauma", label: "Surgery: Trauma" },
    { id: "surgery_trauma_burn", label: "Surgery: Trauma-Burn" },
    { id: "surgery_vascular_primary", label: "Surgery: Vascular (Primary)" },
    { id: "surgical_specialist_physician_rollup", label: "Surgical Specialist Physician Rollup" },
    { id: "urology", label: "Urology" },
    { id: "dental_hygienist", label: "Dental Hygienist" },
    { id: "orthodontics", label: "Orthodontics" },
    { id: "endodontics", label: "Endodontics" },
    { id: "periodontics", label: "Periodontics" },
    { id: "pediatric_dentistry", label: "Pediatric Dentistry" },
    { id: "prosthodontics", label: "Prosthodontics" },
    { id: "oral_maxillofacial_surgery", label: "Oral & Maxillofacial Surgery" },
    { id: "speech_language_pathologist", label: "Speech-Language Pathologist" },
    { id: "radiologic_technologist", label: "Radiologic Technologist" },
    { id: "mri_technologist", label: "MRI Technologist" },
    { id: "ct_technologist", label: "CT Technologist" },
    { id: "diagnostic_medical_sonographer", label: "Diagnostic Medical Sonographer" },
    { id: "respiratory_therapist", label: "Respiratory Therapist" },
    { id: "surgical_technologist", label: "Surgical Technologist" },
    { id: "cardiovascular_technologist", label: "Cardiovascular Technologist" },
    { id: "nuclear_medicine_technologist", label: "Nuclear Medicine Technologist" },
    { id: "medical_laboratory_scientist", label: "Medical Laboratory Scientist" },
    { id: "audiologist", label: "Audiologist" },
    { id: "other", label: "Other", blurb: "Tell us your trail — we route you to the right guide." }
  ],
  /* Mock membership uses common regional groupings; no town or hospital names are implied. */
  regions: [
    { id: "west", label: "West", blurb: "West Coast — California, Oregon, Washington.", states: ["CA", "OR", "WA"] },
    { id: "midwest", label: "Midwest", blurb: "Community pace, solid packages, space to breathe.", states: ["ND", "SD", "NE", "KS", "MN", "IA", "MO", "WI", "IL", "IN", "MI", "OH"] },
    { id: "southwest", label: "Southwest", blurb: "Sunbelt growth markets and employed models.", states: ["TX", "OK"] },
    { id: "southeast", label: "Southeast", blurb: "Coastal and inland options with lifestyle tease.", states: ["AR", "LA", "MS", "AL", "TN", "KY", "GA", "FL", "SC", "NC", "VA", "WV"] },
    { id: "mountain", label: "Mountain West", blurb: "Elevation optional — clarity on schedule required.", states: ["ID", "MT", "WY", "NV", "UT", "CO", "AZ", "NM"] },
    { id: "northeast", label: "Northeast", blurb: "Academic-adjacent and community employed roles.", states: ["PA", "NY", "NJ", "CT", "RI", "MA", "VT", "NH", "ME", "DE", "MD"] },
    { id: "akhi", label: "Alaska & Hawaii", blurb: "Alaska and Hawaii paths with the same guided search experience.", states: ["AK", "HI"] },
    { id: "open", label: "Open", blurb: "Let AMP surface the right ridge for you.", states: [] }
  ],
  facilities: [
    { id: "cah", label: "Critical Access Hospital", blurb: "Rural CAH retained search — AMP works the climb." },
    { id: "dental", label: "Dentistry", blurb: "Dental and DSOs with clear package tease." },
    { id: "group", label: "Medical Group", blurb: "Growth seats with marketing + placement support." },
    { id: "bh", label: "Behavioral Health", blurb: "Behavioral and community behavioral health seats." },
    { id: "fqhc", label: "FQHC", blurb: "Mission-aligned recruiting with clear timelines." },
    { id: "other", label: "Other", blurb: "Tell us the summit you need staffed." },
    { id: "hospital", label: "Hospital / Health system", blurb: "Retained search for hard-to-fill physician roles." }
  ],
  jobs: [
    {
      id: "aca-8368",
      code: "ACA-8368",
      specialty: "anes",
      specialtyLabel: "Anesthesiology - Cardiac",
      region: "southeast",
      state: "Kentucky",
      stateAbbr: "KY",
      title: "$961,000+ First Year Financial Package in a Thriving Midwestern Community",
      sub: "Anesthesiology - Cardiac · ACA-8368 · Kentucky",
      bullets: [
        { k: "Practice", v: "Practice your cardiac anesthesia expertise in a high-volume program where Monday-Friday predictability meets exceptional compensation." },
        { k: "Setting", v: "Kentucky · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/kentucky-cardiac-anesthesiology-aca-8368",
      slug: "kentucky-cardiac-anesthesiology-aca-8368",
    },
    {
      id: "apm-8271",
      code: "APM-8271",
      specialty: "anes",
      specialtyLabel: "Anesthesia Pain Management",
      region: "mountain",
      state: "Nevada",
      stateAbbr: "NV",
      title: "$661,000 Financial Package in Las Vegas, Nevada",
      sub: "Anesthesia Pain Management · APM-8271 · Nevada",
      bullets: [
        { k: "Practice", v: "Build your career with stability, lifestyle, and income few physicians will ever experience." },
        { k: "Setting", v: "Nevada · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/nevada-anesthesia-pain-management-apm-8271",
      slug: "nevada-anesthesia-pain-management-apm-8271",
    },
    {
      id: "cd-7069",
      code: "CD-7069",
      specialty: "cards",
      specialtyLabel: "Cardiology",
      region: "mountain",
      state: "Colorado",
      stateAbbr: "CO",
      title: "$600,000 Base Salary + Bonus Potential | Rare Full-Time Cardiology Opening",
      sub: "Cardiology · CD-7069 · Colorado",
      bullets: [
        { k: "Practice", v: "Step Into a Community That Truly Needs You" },
        { k: "Setting", v: "Colorado · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/colorado-txt-cd-7069",
      slug: "colorado-txt-cd-7069",
    },
    {
      id: "d-8244",
      code: "D-8244",
      specialty: "derm",
      specialtyLabel: "Dermatology",
      region: "west",
      state: "Washington",
      stateAbbr: "WA",
      title: "$620,000+ Dermatology Income in the Northwest",
      sub: "Dermatology · D-8244 · Washington",
      bullets: [
        { k: "Practice", v: "Eight months of patients already waiting — step into instant success." },
        { k: "Setting", v: "Washington · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/washington-dermatology-d-8244",
      slug: "washington-dermatology-d-8244",
    },
    {
      id: "dds-8391",
      code: "DDS-8391",
      specialty: "dental",
      specialtyLabel: "Dentist",
      region: "southeast",
      state: "Louisiana",
      stateAbbr: "LA",
      title: "Up to $300,000 + Loan Forgiveness: Full-Scope Dentistry at Brand New FQHC Clinic",
      sub: "Dentist · DDS-8391 · Louisiana",
      bullets: [
        { k: "Practice", v: "Ready to practice meaningful dentistry in a state-of-the-art facility while making a real difference in underserved communities?" },
        { k: "Setting", v: "Louisiana · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/louisiana-dentist-dds-8391",
      slug: "louisiana-dentist-dds-8391",
    },
    {
      id: "dds-8418",
      code: "DDS-8418",
      specialty: "dental",
      specialtyLabel: "General Dentistry",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $170,000 Base + NHSC Loan Forgiveness: General Dentistry in the Texas Hill Country",
      sub: "General Dentistry · DDS-8418 · Texas",
      bullets: [
        { k: "Practice", v: "$12,000 Sign-On Bonus • Up to $10,000 in Annual Incentives • Four 10s or Five 8s • No Late Nights or Saturdays" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-general-dentistry-dds-8418",
      slug: "texas-general-dentistry-dds-8418",
    },
    {
      id: "em-8433",
      code: "EM-8433",
      specialty: "em",
      specialtyLabel: "Emergency Medicine",
      region: "midwest",
      state: "Kansas",
      stateAbbr: "KS",
      title: "Up to $380,000 + $10,000 Relocation: Emergency Medicine in Central Kansas",
      sub: "Emergency Medicine · EM-8433 · Kansas",
      bullets: [
        { k: "Practice", v: "Three 12-Hour Shifts Weekly • APP & Nursing Support • Metro Access Near Wichita • Malpractice Covered" },
        { k: "Setting", v: "Kansas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/kansas-emergency-medicine-em-8433",
      slug: "kansas-emergency-medicine-em-8433",
    },
    {
      id: "end-8356",
      code: "END-8356",
      specialty: "endo",
      specialtyLabel: "Endocrinology",
      region: "southeast",
      state: "Georgia",
      stateAbbr: "GA",
      title: "$373,750 First-Year Package + No Call in a Charming Southern Community",
      sub: "Endocrinology · END-8356 · Georgia",
      bullets: [
        { k: "Practice", v: "A rare hospital-employed Endocrinology role where work-life balance, income, and lifestyle all line up." },
        { k: "Setting", v: "Georgia · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/georgia-endocrinology-end-8356",
      slug: "georgia-endocrinology-end-8356",
    },
    {
      id: "end-8359",
      code: "END-8359",
      specialty: "endo",
      specialtyLabel: "Endocrinology",
      region: "west",
      state: "Washington",
      stateAbbr: "WA",
      title: "$409,250 First-Year Package in Washington’s Vibrant Wine Country",
      sub: "Endocrinology · END-8359 · Washington",
      bullets: [
        { k: "Practice", v: "Thrive in a respected multispecialty clinic with true work–life balance and a fast-growing patient base." },
        { k: "Setting", v: "Washington · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/washington-endocrinology-end-8359",
      slug: "washington-endocrinology-end-8359",
    },
    {
      id: "fp-8110",
      code: "FP-8110",
      specialty: "fm",
      specialtyLabel: "Family Medicine",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "Up to $260,000+ Starting Salary + Monthly Productivity Bonuses: Family Medicine (Optional OB) in the Monterey Bay Region",
      sub: "Family Medicine · FP-8110 · California",
      bullets: [
        { k: "Practice", v: "4-Day Feel, 5-Day Week • 100% Employer-Paid Insurance • PSLF-Eligible Nonprofit" },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-family-medicine-fp8110",
      slug: "california-family-medicine-fp8110",
    },
    {
      id: "fp-8306",
      code: "FP-8306",
      specialty: "fm",
      specialtyLabel: "Family Medicine",
      region: "west",
      state: "Washington",
      stateAbbr: "WA",
      title: "Up to $303,000 + $90,000 Loan Repayment: Family Medicine in the Heart of Central Washington",
      sub: "Family Medicine · FP-8306 · Washington",
      bullets: [
        { k: "Practice", v: "4-Day Workweek • 7 Weeks PTO • No State Income Tax" },
        { k: "Setting", v: "Washington · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/washington-family-medicine-fp-8306",
      slug: "washington-family-medicine-fp-8306",
    },
    {
      id: "fp-8309",
      code: "FP-8309",
      specialty: "fm",
      specialtyLabel: "Family Medicine",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "$295,000 Guaranteed Base + $75,000 Loan Assistance — 4-Day Week, No Call — Live Minutes from the Beach",
      sub: "Family Medicine · FP-8309 · California",
      bullets: [
        { k: "Practice", v: "Rare California lifestyle role with Friday’s off, visa sponsorship, and big-city fun just down the road." },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-family-practice-fp-8309",
      slug: "california-family-practice-fp-8309",
    },
    {
      id: "fp-8429",
      code: "FP-8429",
      specialty: "fm",
      specialtyLabel: "Family Medicine",
      region: "midwest",
      state: "Michigan",
      stateAbbr: "MI",
      title: "Up to $300,000 + $50,000 Sign-On Bonus: Family Practice in Michigan’s Upper Peninsula",
      sub: "Family Medicine · FP-8429 · Michigan",
      bullets: [
        { k: "Practice", v: "Medical Director Opportunity • 240 Hours PTO • $20,000 Relocation • EPIC EMR" },
        { k: "Setting", v: "Michigan · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/michigan-family-medicine-fp-8429",
      slug: "michigan-family-medicine-fp-8429",
    },
    {
      id: "fp-8450",
      code: "FP-8450",
      specialty: "fm",
      specialtyLabel: "Family Medicine",
      region: "midwest",
      state: "Missouri",
      stateAbbr: "MO",
      title: "From $374,500: Family Medicine in Midwest / Heartland",
      sub: "Family Medicine · FP-8450 · Missouri",
      bullets: [
        { k: "Practice", v: "First-year package from $374,500 — full details on a brief call with your recruiter" },
        { k: "Setting", v: "Missouri · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/midwest-family-medicine-fp-8450",
      slug: "midwest-family-medicine-fp-8450",
    },
    {
      id: "fpob-8385",
      code: "FPOB-8385",
      specialty: "obg",
      specialtyLabel: "Family Medicine - Obstetrics",
      region: "west",
      state: "Oregon",
      stateAbbr: "OR",
      title: "Up to $431,250 First-Year Financial Package: Family Medicine with Obstetrics in the Mountain West",
      sub: "Family Medicine - Obstetrics · FPOB-8385 · Oregon",
      bullets: [
        { k: "Practice", v: "4-Day Workweek • Sign-On + Relocation • NHSC Loan Repayment Eligible • Established FPOB Need" },
        { k: "Setting", v: "Oregon · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/oregon-family-medicine-obstetrics-fpob-8385",
      slug: "oregon-family-medicine-obstetrics-fpob-8385",
    },
    {
      id: "ge-8325",
      code: "GE-8325",
      specialty: "gi",
      specialtyLabel: "Gastroenterology",
      region: "southeast",
      state: "Arkansas",
      stateAbbr: "AR",
      title: "$887,500+ First-Year Package: High-Volume GI Practice with ERCP in East Texas",
      sub: "Gastroenterology · GE-8325 · Arkansas",
      bullets: [
        { k: "Practice", v: "What if you could earn nearly $900K your first year while maintaining excellent work-life balance and buying a home for under $200K?" },
        { k: "Setting", v: "Arkansas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-gastroenterology-ge-8325",
      slug: "texas-gastroenterology-ge-8325",
    },
    {
      id: "ge-8409",
      code: "GE-8409",
      specialty: "gi",
      specialtyLabel: "Gastroenterology",
      region: "southeast",
      state: "North Carolina",
      stateAbbr: "NC",
      title: "Up to $786,250 First Year Financial Package: Gastroenterology in the Coastal Southeast",
      sub: "Gastroenterology · GE-8409 · North Carolina",
      bullets: [
        { k: "Practice", v: "4.5-Day Workweek • Extremely Light Call • Established Patient Base • Coastal Carolina Lifestyle" },
        { k: "Setting", v: "North Carolina · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/north-carolina-gastroenterology-ge-8409",
      slug: "north-carolina-gastroenterology-ge-8409",
    },
    {
      id: "hfc-8398",
      code: "HFC-8398",
      specialty: "cards",
      specialtyLabel: "Cardiology",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $600,000+ RVU Growth: Heart Failure Cardiology in North Texas",
      sub: "Cardiology · HFC-8398 · Texas",
      bullets: [
        { k: "Practice", v: "1:7 Call with APP First-Call • Protected Consult Weeks • Predictable 8:30–4:00 Schedule • 28 Days PTO" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-cardiology-hfc-8398",
      slug: "texas-cardiology-hfc-8398",
    },
    {
      id: "hfc-8399",
      code: "HFC-8399",
      specialty: "cards",
      specialtyLabel: "Cardiology - Interventional",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $600,000 Financial Package + Main Hospital Focus: Heart Failure Opportunity in Dallas",
      sub: "Cardiology - Interventional · HFC-8399 · Texas",
      bullets: [
        { k: "Practice", v: "Main Hospital Only • Inpatient HF Program Growth • Advanced Therapies Exposure • No State Income Tax" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-interventional-cardiology-hfc-8399",
      slug: "texas-interventional-cardiology-hfc-8399",
    },
    {
      id: "ho-8194",
      code: "HO-8194",
      specialty: "hemeonc",
      specialtyLabel: "Hematology / Oncology",
      region: "midwest",
      state: "Indiana",
      stateAbbr: "IN",
      title: "$889,000 Income + $100,000 Sign-On for Medical Oncologist Minutes from Indianapolis",
      sub: "Hematology / Oncology · HO-8194 · Indiana",
      bullets: [
        { k: "Practice", v: "High-income, low-cost living, true autonomy—build your ideal oncology practice in a captured market." },
        { k: "Setting", v: "Indiana · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/indiana-hematology-oncology-ho-8194",
      slug: "indiana-hematology-oncology-ho-8194",
    },
    {
      id: "ho-8370",
      code: "HO-8370",
      specialty: "hemeonc",
      specialtyLabel: "Hematology / Oncology",
      region: "southeast",
      state: "Kentucky",
      stateAbbr: "KY",
      title: "Up to $650,000 + $100,000 Sign-On + Loan Repayment: Hematology/Oncology in the Midwest",
      sub: "Hematology / Oncology · HO-8370 · Kentucky",
      bullets: [
        { k: "Practice", v: "4-Day Workweek • Outpatient-Focused Practice • Epic EMR • Minimal Call (2–3 Weeks/Year) • $25K Annual Loan Repayment • Strong APP and Infusion Support" },
        { k: "Setting", v: "Kentucky · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/kentucky-hematology-oncology-ho-8370",
      slug: "kentucky-hematology-oncology-ho-8370",
    },
    {
      id: "ivc-8349",
      code: "IVC-8349",
      specialty: "cards",
      specialtyLabel: "Cardiology - Interventional",
      region: "southeast",
      state: "Alabama",
      stateAbbr: "AL",
      title: "$975,000 First-Year Package + Lifestyle Schedule — Interventional Cardiology in the Southeast",
      sub: "Cardiology - Interventional · IVC-8349 · Alabama",
      bullets: [
        { k: "Practice", v: "Rare chance to join a highly supported, accredited Cath Lab with a flexible schedule in a beautiful, affordable community." },
        { k: "Setting", v: "Alabama · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/alabama-interventional-cardiology-ivc-8349",
      slug: "alabama-interventional-cardiology-ivc-8349",
    },
    {
      id: "ivc-8369",
      code: "IVC-8369",
      specialty: "cards",
      specialtyLabel: "Cardiology - Interventional",
      region: "southeast",
      state: "Kentucky",
      stateAbbr: "KY",
      title: "$1,058,750+ Interventional Cardiology: Join Elite Program with 8 Cath Labs",
      sub: "Cardiology - Interventional · IVC-8369 · Kentucky",
      bullets: [
        { k: "Practice", v: "Break the seven-figure barrier in your first year while practicing cutting-edge interventional cardiology in state-of-the-art facilities." },
        { k: "Setting", v: "Kentucky · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/kentucky-interventional-cardiology-ivc-8369",
      slug: "kentucky-interventional-cardiology-ivc-8369",
    },
    {
      id: "ivc-8397",
      code: "IVC-8397",
      specialty: "cards",
      specialtyLabel: "Cardiology - Interventional",
      region: "mountain",
      state: "New Mexico",
      stateAbbr: "NM",
      title: "Up to $925,000+ First-Year Package: Cardiology in the Mountain West",
      sub: "Cardiology - Interventional · IVC-8397 · New Mexico",
      bullets: [
        { k: "Practice", v: "3-Day Clinic • 2-Day ASC • Established Procedural Volume • Partnership Culture" },
        { k: "Setting", v: "New Mexico · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/new-mexico-cardiology-interventional-ivc-8397",
      slug: "new-mexico-cardiology-interventional-ivc-8397",
    },
    {
      id: "ivc-8404",
      code: "IVC-8404",
      specialty: "cards",
      specialtyLabel: "Cardiology - Interventional",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $700,000 Base + Partnership Track: Interventional Cardiology in East Texas",
      sub: "Cardiology - Interventional · IVC-8404 · Texas",
      bullets: [
        { k: "Practice", v: "High Demand • New Cath Lab • Rapid Ramp-Up • Private Practice–Aligned Model" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-interventional-cardiology-ivc-8404",
      slug: "texas-interventional-cardiology-ivc-8404",
    },
    {
      id: "n-8347",
      code: "N-8347",
      specialty: "neuro",
      specialtyLabel: "Neurology",
      region: "southeast",
      state: "Alabama",
      stateAbbr: "AL",
      title: "$487,250 First Year Financial Package in the Southeast",
      sub: "Neurology · N-8347 · Alabama",
      bullets: [
        { k: "Practice", v: "Four-Day Work Week + Scenic Riverfront Community Living" },
        { k: "Setting", v: "Alabama · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/alabama-neurology-n-8347",
      slug: "alabama-neurology-n-8347",
    },
    {
      id: "n-8358",
      code: "N-8358",
      specialty: "neuro",
      specialtyLabel: "Neurology",
      region: "southeast",
      state: "Georgia",
      stateAbbr: "GA",
      title: "$593,750 + Zero Call: Outpatient Neurology with Friday Half-Days in Southeast",
      sub: "Neurology · N-8358 · Georgia",
      bullets: [
        { k: "Practice", v: "Imagine practicing neurology with no hospital call, high procedure volume, and your clinic closing by noon every Friday." },
        { k: "Setting", v: "Georgia · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/georgia-neurology-n-8358",
      slug: "georgia-neurology-n-8358",
    },
    {
      id: "n-8411",
      code: "N-8411",
      specialty: "neuro",
      specialtyLabel: "Neurology",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $375,000 Base + wRVU Bonus: Outpatient Neurology in West Texas (Midland Area)",
      sub: "Neurology · N-8411 · Texas",
      bullets: [
        { k: "Practice", v: "4.5-Day Week • Fridays End at Noon • 100% Outpatient • Minimal Call" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-neurology-n-8411",
      slug: "texas-neurology-n-8411",
    },
    {
      id: "np-8224",
      code: "NP-8224",
      specialty: "np",
      specialtyLabel: "Nurse Practitioner",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "$263,000 First-Year Package in Beautiful Central California",
      sub: "Nurse Practitioner · NP-8224 · California",
      bullets: [
        { k: "Practice", v: "Live minutes from Monterey, Pebble Beach, and Carmel while making a true community impact!" },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-nurse-practitioner-np-8224",
      slug: "california-nurse-practitioner-np-8224",
    },
    {
      id: "np-8229",
      code: "NP-8229",
      specialty: "np",
      specialtyLabel: "Nurse Practitioner",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "$179,087 First-Year Package + 6 Weeks PTO in Central Washington",
      sub: "Nurse Practitioner · NP-8229 · California",
      bullets: [
        { k: "Practice", v: "Thrive in a supportive, team-based Primary Care practice while enjoying the lifestyle you deserve." },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-nurse-practitioner-np-8229",
      slug: "california-nurse-practitioner-np-8229",
    },
    {
      id: "np-8250",
      code: "NP-8250",
      specialty: "np",
      specialtyLabel: "Nurse Practitioner",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "Bay Area Family Nurse Practitioner—4- or 5-Day Week, No Call, and Six Weeks PTO",
      sub: "Nurse Practitioner · NP-8250 · California",
      bullets: [
        { k: "Practice", v: "Join a patient-centered, fast-growing healthcare organization where work-life balance isn’t a perk—it’s the plan." },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-nurse-practitioner-np-8250",
      slug: "california-nurse-practitioner-np-8250",
    },
    {
      id: "obg-8180",
      code: "OBG-8180",
      specialty: "obg",
      specialtyLabel: "Obstetrics and Gynecology",
      region: "midwest",
      state: "Indiana",
      stateAbbr: "IN",
      title: "$475,000 OBGYN Lakeside Lifestyle – Before Bonuses!",
      sub: "Obstetrics and Gynecology · OBG-8180 · Indiana",
      bullets: [
        { k: "Practice", v: "Flexible schedule, robotic access, and an award-winning birthing center await." },
        { k: "Setting", v: "Indiana · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/indiana-obstetrics-and-gynecology-obg-8180",
      slug: "indiana-obstetrics-and-gynecology-obg-8180",
    },
    {
      id: "obg-8316",
      code: "OBG-8316",
      specialty: "obg",
      specialtyLabel: "Obstetrics and Gynecology",
      region: "southwest",
      state: "Oklahoma",
      stateAbbr: "OK",
      title: "OBGYN Opportunity in Scenic Oklahoma – Competitive Compensation + True Work-Life Balance",
      sub: "Obstetrics and Gynecology · OBG-8316 · Oklahoma",
      bullets: [
        { k: "Practice", v: "Practice medicine without production pressure in a community that values your expertise." },
        { k: "Setting", v: "Oklahoma · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/oklahoma-obstetrics-and-gynecology-obg-8316",
      slug: "oklahoma-obstetrics-and-gynecology-obg-8316",
    },
    {
      id: "obg-8321",
      code: "OBG-8321",
      specialty: "obg",
      specialtyLabel: "Obstetrics and Gynecology",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $350,000 + RVU Upside: OB/GYN in Central Texas (90 Minutes from DFW)",
      sub: "Obstetrics and Gynecology · OBG-8321 · Texas",
      bullets: [
        { k: "Practice", v: "1:4 Call • 28 Days PTO • Da Vinci XI • Only OB Group in the Region" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/tennessee-obstetrics-and-gynecology-obg-8321",
      slug: "tennessee-obstetrics-and-gynecology-obg-8321",
    },
    {
      id: "obg-8422",
      code: "OBG-8422",
      specialty: "obg",
      specialtyLabel: "Obstetrics and Gynecology",
      region: "southeast",
      state: "Alabama",
      stateAbbr: "AL",
      title: "Up to $500,000 Guaranteed + $100,000 Loan Repayment: OB/GYN in North Alabama",
      sub: "Obstetrics and Gynecology · OBG-8422 · Alabama",
      bullets: [
        { k: "Practice", v: "$500,000 Guaranteed Base • $30,000 Sign-On Bonus • Robotics Available • 29 Days PTO + CME" },
        { k: "Setting", v: "Alabama · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/alabama-obstetrics-and-gynecology-obg-8422",
      slug: "alabama-obstetrics-and-gynecology-obg-8422",
    },
    {
      id: "obg-8449",
      code: "OBG-8449",
      specialty: "obg",
      specialtyLabel: "Obstetrics and Gynecology",
      region: "midwest",
      state: "Missouri",
      stateAbbr: "MO",
      title: "From $812,000: OB/GYN in Midwest",
      sub: "Obstetrics and Gynecology · OBG-8449 · Missouri",
      bullets: [
        { k: "Practice", v: "First-year package from $812,000 — full details on a brief call with your recruiter" },
        { k: "Setting", v: "Missouri · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 8 },
      url: "https://www.adaptivemedicalpartners.com/job/midwest-obstetrics-and-gynecology-obg-8449",
      slug: "midwest-obstetrics-and-gynecology-obg-8449",
    },
    {
      id: "od-8364",
      code: "OD-8364",
      specialty: "opt",
      specialtyLabel: "Optometry",
      region: "southeast",
      state: "Louisiana",
      stateAbbr: "LA",
      title: "$150,000-$175,000: Found Your Own Optometry Program in Brand New Clinic",
      sub: "Optometry · OD-8364 · Louisiana",
      bullets: [
        { k: "Practice", v: "Shape the future of vision care for thousands of Louisiana families while building your ideal practice from day one." },
        { k: "Setting", v: "Louisiana · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/louisiana-optometry-od-8364",
      slug: "louisiana-optometry-od-8364",
    },
    {
      id: "ot-8388",
      code: "OT-8388",
      specialty: "ot",
      specialtyLabel: "Occupational Therapy",
      region: "west",
      state: "Oregon",
      stateAbbr: "OR",
      title: "Up to $58/hr + $15,000 Retention Bonus: Occupational Therapist in Eastern Oregon’s Blue Mountain Region",
      sub: "Occupational Therapy · OT-8388 · Oregon",
      bullets: [
        { k: "Practice", v: "1:1 Patient Care • 45–60 Minute Sessions • $2K CME + 5% Match • Affordable Mountain Living" },
        { k: "Setting", v: "Oregon · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/oregon-occupational-therapy",
      slug: "oregon-occupational-therapy",
    },
    {
      id: "oto-8371",
      code: "OTO-8371",
      specialty: "surg",
      specialtyLabel: "Otolaryngology",
      region: "southeast",
      state: "Kentucky",
      stateAbbr: "KY",
      title: "$682,500 ENT Position: 3 Clinic Days, 2 OR Days in Tri-State Region",
      sub: "Otolaryngology · OTO-8371 · Kentucky",
      bullets: [
        { k: "Practice", v: "High-volume ENT practice meets exceptional work-life balance—finally, a role where you can excel professionally without sacrificing your personal life." },
        { k: "Setting", v: "Kentucky · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 8, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/kentucky-otolaryngology-oto-8371",
      slug: "kentucky-otolaryngology-oto-8371",
    },
    {
      id: "p-8191",
      code: "P-8191",
      specialty: "psych",
      specialtyLabel: "Psychiatry",
      region: "mountain",
      state: "Arizona",
      stateAbbr: "AZ",
      title: "$380,000 Forensic Psychiatry Position: 50-Year Established Program in Tucson",
      sub: "Psychiatry · P-8191 · Arizona",
      bullets: [
        { k: "Practice", v: "Tired of the same outpatient cases? Ready for intellectually stimulating forensic work with exceptional benefits?" },
        { k: "Setting", v: "Arizona · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 8, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/arizona-psychiatry-p-8191",
      slug: "arizona-psychiatry-p-8191",
    },
    {
      id: "pa-8226",
      code: "PA-8226",
      specialty: "pa",
      specialtyLabel: "Physician Assistant",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "$242,500 First-Year Financial Package in Beautiful Monterey County, California",
      sub: "Physician Assistant · PA-8226 · California",
      bullets: [
        { k: "Practice", v: "Make a lasting impact while living the coastal California lifestyle you’ve always dreamed of." },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-physician-assistant-pa-8226",
      slug: "california-physician-assistant-pa-8226",
    },
    {
      id: "pd-8403",
      code: "PD-8403",
      specialty: "peds",
      specialtyLabel: "Pediatrics",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $250,000 Base + Productivity Bonuses: Pediatrics in Northeast Texas",
      sub: "Pediatrics · PD-8403 · Texas",
      bullets: [
        { k: "Practice", v: "4–5 Day Workweek Options • Predictable Call • FQHC Loan Repayment up to $50,000/Year" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-pediatrics-pd-8403",
      slug: "texas-pediatrics-pd-8403",
    },
    {
      id: "pt-8387",
      code: "PT-8387",
      specialty: "other",
      specialtyLabel: "Physical Therapy",
      region: "west",
      state: "Oregon",
      stateAbbr: "OR",
      title: "Up to $58/Hour + $10,000 Retention Bonus: Physical Therapist in Eastern Oregon Mountain Valley",
      sub: "Physical Therapy · PT-8387 · Oregon",
      bullets: [
        { k: "Practice", v: "Four-Day Workweek Available • 100% One-on-One Care • 5 Paid Admin Hours Weekly • $2,000 CE + Education Time • Interdisciplinary Team • Relocation Support" },
        { k: "Setting", v: "Oregon · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/oregon-physical-therapy-pt-8387",
      slug: "oregon-physical-therapy-pt-8387",
    },
    {
      id: "pud-8348",
      code: "PUD-8348",
      specialty: "pulm",
      specialtyLabel: "Pulmonology",
      region: "southeast",
      state: "Alabama",
      stateAbbr: "AL",
      title: "$566,250 First-Year Package + 4-Day Work Week in the Heart of the Southeast",
      sub: "Pulmonology · PUD-8348 · Alabama",
      bullets: [
        { k: "Practice", v: "Rare lifestyle-friendly pulmonology opportunity with immediate volume, procedures, and a supportive, well-funded team." },
        { k: "Setting", v: "Alabama · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/alabama-pulmonology-pud-8348",
      slug: "alabama-pulmonology-pud-8348",
    },
    {
      id: "rad-8256",
      code: "RAD-8256",
      specialty: "rad",
      specialtyLabel: "Radiology",
      region: "west",
      state: "California",
      stateAbbr: "CA",
      title: "$744,000 First-Year Package Just Minutes from Southern California",
      sub: "Radiology · RAD-8256 · California",
      bullets: [
        { k: "Practice", v: "A rare chance to join a thriving radiology group offering partnership after just one year!" },
        { k: "Setting", v: "California · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Mike Freeman",
        phone: "972-532-0355",
        email: "mfreeman@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/california-radiology-rad-8256",
      slug: "california-radiology-rad-8256",
    },
    {
      id: "rhu-8345",
      code: "RHU-8345",
      specialty: "rheum",
      specialtyLabel: "Rheumatology",
      region: "southeast",
      state: "Alabama",
      stateAbbr: "AL",
      title: "$389,750 First Year Package in Scenic Southeast Alabama",
      sub: "Rheumatology · RHU-8345 · Alabama",
      bullets: [
        { k: "Practice", v: "Four-day work week, no competition, and immediate patient demand." },
        { k: "Setting", v: "Alabama · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/alabama-rheumatology-rhu-8345",
      slug: "alabama-rheumatology-rhu-8345",
    },
    {
      id: "rhu-8365",
      code: "RHU-8365",
      specialty: "rheum",
      specialtyLabel: "Rheumatology",
      region: "southeast",
      state: "Louisiana",
      stateAbbr: "LA",
      title: "Up to $350,000: Build Your Own Rheumatology Program from Day One",
      sub: "Rheumatology · RHU-8365 · Louisiana",
      bullets: [
        { k: "Practice", v: "Be the only rheumatologist serving six Louisiana parishes—with zero competition, built-in referrals, and modern facilities waiting for you." },
        { k: "Setting", v: "Louisiana · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/louisiana-rheumatology-rhu-8365",
      slug: "louisiana-rheumatology-rhu-8365",
    },
    {
      id: "rtech-8273",
      code: "RTECH-8273",
      specialty: "rad",
      specialtyLabel: "Radiology Technician",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "$109,200 First Year Financial Package in West Texas",
      sub: "Radiology Technician · RTECH-8273 · Texas",
      bullets: [
        { k: "Practice", v: "Rewarding work, no call, and a community that feels like home." },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Nate Smith",
        phone: "214-929-9555",
        email: "nsmith@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-radiology-technician-rtech-8273",
      slug: "texas-radiology-technician-rtech-8273",
    },
    {
      id: "rtech-8447",
      code: "RTECH-8447",
      specialty: "rad",
      specialtyLabel: "RTECH: Radiology Technician",
      region: "mountain",
      state: "Arizona",
      stateAbbr: "AZ",
      title: "CT Tech: $115,000+ First Year Financial Package",
      sub: "RTECH: Radiology Technician · RTECH-8447 · Arizona",
      bullets: [
        { k: "Practice", v: "Practice: Established and Well-Funded Organization" },
        { k: "Setting", v: "Arizona · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/arizona-rtech-radiology-technician-rtech8447",
      slug: "arizona-rtech-radiology-technician-rtech8447",
    },
    {
      id: "st-8313",
      code: "ST-8313",
      specialty: "other",
      specialtyLabel: "Speech Therapy",
      region: "southwest",
      state: "Oklahoma",
      stateAbbr: "OK",
      title: "HYBRID Schedule – Only 2 Days Onsite Per Week!",
      sub: "Speech Therapy · ST-8313 · Oklahoma",
      bullets: [
        { k: "Practice", v: "Enjoy flexibility, support, and growth in a uniquely rewarding practice." },
        { k: "Setting", v: "Oklahoma · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/oklahoma-speech-therapy-st-8313",
      slug: "oklahoma-speech-therapy-st-8313",
    },
    {
      id: "st-8389",
      code: "ST-8389",
      specialty: "other",
      specialtyLabel: "Speech Language Pathology",
      region: "west",
      state: "Oregon",
      stateAbbr: "OR",
      title: "Up to $58/Hour + $15,000 Retention Bonus: Speech Language Pathologist in Eastern Oregon",
      sub: "Speech Language Pathology · ST-8389 · Oregon",
      bullets: [
        { k: "Practice", v: "4-Day Workweek • 5 Hours Paid Admin Time Weekly • Family-Like Rehab Team • No Competition in the Area" },
        { k: "Setting", v: "Oregon · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Amy Myers",
        phone: "972-301-2261",
        email: "amyers@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-3.jpg",
      summit: { practice: 6, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/oregon-speech-language-pathology-st-8389",
      slug: "oregon-speech-language-pathology-st-8389",
    },
    {
      id: "u-8357",
      code: "U-8357",
      specialty: "uro",
      specialtyLabel: "Urology",
      region: "southeast",
      state: "Georgia",
      stateAbbr: "GA",
      title: "$943,750 First-Year Package + Minimal Call in a Modern, Well-Resourced Southeastern Health System",
      sub: "Urology · U-8357 · Georgia",
      bullets: [
        { k: "Practice", v: "Rare urology role with blockbuster bonuses, robotic support, and true lifestyle flexibility in a thriving Southern community." },
        { k: "Setting", v: "Georgia · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Hadley Herrera",
        phone: "972-532-0465",
        email: "hherrera@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-1.jpg",
      summit: { practice: 8, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/georgia-urology-u-8357",
      slug: "georgia-urology-u-8357",
    },
    {
      id: "u-8410",
      code: "U-8410",
      specialty: "uro",
      specialtyLabel: "Urology",
      region: "southwest",
      state: "Texas",
      stateAbbr: "TX",
      title: "Up to $750,000 Base + Paid Call + Future ASC Buy-In: Urology in West Texas",
      sub: "Urology · U-8410 · Texas",
      bullets: [
        { k: "Practice", v: "Robotics + Aquablation • 1–2 OR Days/Week • No State Income Tax • $30K Sign-On + $15K Relocation" },
        { k: "Setting", v: "Texas · location sprinkle, not the whole pitch" },
        { k: "Package", v: "Compensation and stack gated behind contact on purpose" },
        { k: "Next", v: "Tap to Talk / Text / Email — AMP routes you to the right guide" },
      ],
      recruiter: {
        name: "Stephanie Youngblood",
        phone: "469-354-0386",
        email: "syoungblood@adaptivemedicalpartners.com",
        cc: "inquire@adaptivemedicalpartners.com"
      },
      hero: "assets/mike-ridge-2.jpg",
      summit: { practice: 8, life: 6, location: 6, income: 6 },
      url: "https://www.adaptivemedicalpartners.com/job/texas-urology-u-8410",
      slug: "texas-urology-u-8410",
    }
  ],
  posts: [
    { slug: "first-job-shortfalls-residents-fellows", title: "First-Job Shortfalls Residents and Fellows Should Spot Before They Sign", meta: "A practical first-job checklist for residents and fellows: schedule, support, contract literacy, and the questions that protect the first climb.", byline: "Michael Freeman", tags: ["Residents", "Fellows", "Career"], mins: 8 },
    { slug: "place-first-without-regret", title: "Place First Without Regret: Choose the Life Around the Practice", meta: "How residents and fellows can evaluate place-first fit without inventing a town story or falling for a postcard.", byline: "Randy Keeth", tags: ["Residents", "Place", "Career"], mins: 7 },
    { slug: "two-year-test-before-you-sign", title: "The Two-Year Test Before You Sign Your First Physician Contract", meta: "A two-year audit for residents and fellows: test the week, contract mechanics, support, and your second-climb signal.", byline: "Michael Freeman", tags: ["Contracts", "Residents", "Education"], mins: 8 },
    { slug: "mpc-when-location-leads", title: "MPC: When Location Leads the Conversation", meta: "A mountain-voice guide to MPC when place is the first filter—and when a retained guide makes the climb safer.", byline: "Michael Freeman", tags: ["MPC", "Place", "Residents"], mins: 7 },
    { slug: "coordinator-share-pack-grads", title: "A Coordinator’s Share Pack for New Graduates", meta: "A short, practical share pack program coordinators can give graduating residents and fellows before the first job search.", byline: "Adaptive Medical Partners", tags: ["Coordinators", "Graduates", "Education"], mins: 5 },
    {
      slug: "physician-retention-3-year-kpi",
      title: "Why Is 3-Year Physician Retention the Real KPI — Not Just ‘Filled’?",
      meta: "Why do stay rates beat time-to-fill? Adaptive Medical Partners cites 87% physician retention at three years — the mountain KPI that protects patients, budgets, and culture.",
      tags: ["Retention", "Hospitals", "Education"],
      mins: 11
    },
    {
      slug: "interview-to-placement-efficiency",
      title: "What Does 1.7 Interviews per Placement Mean for Hospitals?",
      meta: "What does AMP’s 1.7 average interviews per successful placement mean? Why interview efficiency beats resume volume — and how retained guides stage prepared hikers at the summit.",
      tags: ["Interview efficiency", "Retained search", "Education"],
      mins: 10
    },
    {
      slug: "rural-fqhc-critical-access-recruiting",
      title: "How Do You Recruit for Rural, FQHC & Critical Access Roles?",
      meta: "How should hospitals approach rural, FQHC, and critical access physician recruiting? AMP cites 700+ community partnerships — a practical guide without invented town names.",
      tags: ["Rural", "FQHC", "Critical access"],
      mins: 11
    },
    {
      slug: "retained-vs-contingent-physician-search",
      title: "Retained or Contingent Physician Search: Which Model Should Hospitals Choose?",
      meta: "Which physician search model fits — retained or contingent? Compare accountability, marketing, and how Adaptive Medical Partners guides both sides of the mountain.",
      tags: ["Retained search", "Hospitals", "Education"],
      mins: 9
    },
    {
      slug: "evaluate-obgyn-opportunities",
      title: "How to Evaluate OB/GYN Opportunities Without Getting Lost in the Brochure",
      meta: "A physician-first checklist for evaluating OB/GYN jobs: schedule reality, call burden, income structure, and when to talk to a guide like AMP before deciding.",
      tags: ["OB/GYN", "Physicians", "Career"],
      mins: 8
    },
    {
      slug: "amp-score-explained",
      title: "What Is AMP Score — and How Does It Rank Opportunity Fit?",
      meta: "What is AMP Score? How physicians and organizations quantify fit across lifestyle, practice design, compensation clarity, and culture — without dumping full dossiers publicly.",
      tags: ["AMP Score", "Product", "Fit"],
      mins: 7
    },
    {
      slug: "midwest-lifestyle-for-physicians",
      title: "What Does Midwest Lifestyle for Physicians Usually Leave Out?",
      meta: "What does Midwest physician lifestyle marketing usually leave out? Commute reality, schools, weekday endings, and how to pressure-test community roles with a retained guide.",
      tags: ["Midwest", "Lifestyle", "Physicians"],
      mins: 8
    },
    {
      slug: "what-hospitals-should-ask-retained-firm",
      title: "What Hospitals Should Ask a Retained Physician Search Firm Before Signing",
      meta: "Twelve questions hospitals and medical groups should ask any retained firm — including AMP — about process, marketing, candidate quality, and summit meeting readiness.",
      tags: ["Organizations", "Retained", "BD"],
      mins: 10
    },
    {
      slug: "candidate-interview-prep-without-leaks",
      title: "How Do You Prep for Physician Interviews Without Leaking Confidential Details?",
      meta: "How can physicians prep for interviews without leaking client-specific details? AMP’s no-leaks playbook for confident, ethical conversations.",
      tags: ["Candidates", "Interview", "Confidential"],
      mins: 8
    }
  ],
  mpcInventory: {
    sampleNote: "Illustrative sample inventory counts",
    profiles: 47,
    specialties: 12,
    corridors: "metro corridors nationwide"
  },
  mpcLookingRegions: [
    { id: "midwest-metro", label: "Midwest metros" },
    { id: "southwest-metro", label: "Southwest metros" },
    { id: "southeast-metro", label: "Southeast metros" },
    { id: "mountain-metro", label: "Mountain West metros" },
    { id: "northeast-metro", label: "Northeast metros" },
    { id: "open-metro", label: "Open · metro-first" }
  ],
  mpcCandidates: [
    {
      id: "mpc-a",
      alias: "Physician A",
      initials: "A.R.",
      specialty: "Family Medicine",
      specialtyId: "fm",
      looking: "Midwest metros",
      lookingId: "midwest-metro",
      metroOnly: true,
      trainingBlur: "████ Residency · Midwest · 20██–20██",
      dossierTease: "Outpatient-leaning · open to employed metro group · schedule clarity first",
      cvStub: "Board-certified FM · █ years post-training · redacted CV on file",
      sections: [
        { label: "Practice preference", value: "Clinic-first weeks · limited inpatient" },
        { label: "Looking toward", value: "Midwest metro corridors" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Active · multi-state interest · details gated" }
      ]
    },
    {
      id: "mpc-b",
      alias: "Physician B",
      initials: "B.K.",
      specialty: "OB/GYN",
      specialtyId: "obg",
      looking: "Southwest metros",
      lookingId: "southwest-metro",
      metroOnly: true,
      trainingBlur: "████ OB/GYN · Southwest · Class of 20██",
      dossierTease: "Employed OB · weekday rhythm preference · metro amenities matter",
      cvStub: "OB/GYN · GYN-heavy option open · redacted package",
      sections: [
        { label: "Practice preference", value: "Employed OB with sustainable call" },
        { label: "Looking toward", value: "Southwest growth metros" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Board-certified · details gated" }
      ]
    },
    {
      id: "mpc-c",
      alias: "Physician C",
      initials: "C.M.",
      specialty: "Psychiatry",
      specialtyId: "psych",
      looking: "Northeast metros",
      lookingId: "northeast-metro",
      metroOnly: true,
      trainingBlur: "████ Psychiatry · Northeast · Fellowship ███",
      dossierTease: "Outpatient / hybrid psych · metro access to culture & transit",
      cvStub: "Psychiatry · hybrid-friendly · redacted CV",
      sections: [
        { label: "Practice preference", value: "Outpatient-first · hybrid optional" },
        { label: "Looking toward", value: "Northeast metros" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Active · details gated" }
      ]
    },
    {
      id: "mpc-d",
      alias: "Physician D",
      initials: "D.S.",
      specialty: "Hospitalist",
      specialtyId: "hosp",
      looking: "Southeast metros",
      lookingId: "southeast-metro",
      metroOnly: true,
      trainingBlur: "████ IM · Hospitalist track · 20██",
      dossierTease: "7-on / 7-off block · metro hospital systems",
      cvStub: "Hospitalist · block schedule preferred · redacted",
      sections: [
        { label: "Practice preference", value: "Block schedule hospitalist" },
        { label: "Looking toward", value: "Southeast metro hospitals" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Board-certified IM · gated" }
      ]
    },
    {
      id: "mpc-e",
      alias: "Physician E",
      initials: "E.T.",
      specialty: "Internal Medicine",
      specialtyId: "im",
      looking: "Mountain West metros",
      lookingId: "mountain-metro",
      metroOnly: true,
      trainingBlur: "████ IM · Mountain West · 20██–20██",
      dossierTease: "Employed IM · elevation optional · metro amenities required",
      cvStub: "Internal Medicine · outpatient lean · redacted CV",
      sections: [
        { label: "Practice preference", value: "Outpatient IM · team-based" },
        { label: "Looking toward", value: "Mountain West metros" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Active · details gated" }
      ]
    },
    {
      id: "mpc-f",
      alias: "Physician F",
      initials: "F.L.",
      specialty: "Family Medicine",
      specialtyId: "fm",
      looking: "Open · metro-first",
      lookingId: "open-metro",
      metroOnly: true,
      trainingBlur: "████ FM · ████ · Class of 20██",
      dossierTease: "Metro-first FM · open corridor · lifestyle filter strong",
      cvStub: "Family Medicine · █ yrs · redacted",
      sections: [
        { label: "Practice preference", value: "Outpatient FM · no OB required" },
        { label: "Looking toward", value: "Any strong metro corridor" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Multi-state interest · gated" }
      ]
    },
    {
      id: "mpc-g",
      alias: "Physician G",
      initials: "G.P.",
      specialty: "OB/GYN",
      specialtyId: "obg",
      looking: "Midwest metros",
      lookingId: "midwest-metro",
      metroOnly: true,
      trainingBlur: "████ OB/GYN · Midwest · 20██",
      dossierTease: "Full-scope OB open · prefers metro hospital affiliation",
      cvStub: "OB/GYN · full-scope · redacted stub",
      sections: [
        { label: "Practice preference", value: "Full-scope OB/GYN" },
        { label: "Looking toward", value: "Midwest metros" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Board-eligible/certified · gated" }
      ]
    },
    {
      id: "mpc-h",
      alias: "Physician H",
      initials: "H.N.",
      specialty: "Psychiatry",
      specialtyId: "psych",
      looking: "Southwest metros",
      lookingId: "southwest-metro",
      metroOnly: false,
      trainingBlur: "████ Psychiatry · Sunbelt · 20██",
      dossierTease: "Adult psych · open to metro-adjacent with strong amenities",
      cvStub: "Psychiatry · adult · redacted CV on file",
      sections: [
        { label: "Practice preference", value: "Adult outpatient psych" },
        { label: "Looking toward", value: "Southwest metros + metro-adjacent" },
        { label: "Training", value: "████████████ · redacted" },
        { label: "Licensure", value: "Active · details gated" }
      ]
    }
  ]
};
